baseurl                  = "/"           # Your domain name. Must end with "/". https://www.javierorraca.com
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Javier Orraca // Data Analyst"
theme                    = "hugo-theme-sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
googleAnalytics          = "UA-127790709-3"                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "2006 Jan 02"
    dateformfull         = "2006 Jan 02 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "Javier Orraca // Data Analyst"

# Metadata for Open Graph and Twitter
    description          = "Javier Orraca's Data Science resource hub."               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Hi, I'm Javier."

[[params.mainMenu]]
    link = "/blog"
    text = "blog"

[[params.mainMenu]]
    link = "/scatterpodcast"
    text = "scatter podcast"

[[params.mainMenu]]
    link = "/consulting"
    text = "consulting"

[[params.mainMenu]]
    link = "/contact"
    text = "contact"

[[params.mainMenu]]
    link = "/about"
    text = "who is javier?"

[imaging]
    quality = 75
